Customer.create(first_name: 'Luke', last_name:'John', email: 'lukejohn@gmail.com')


Currency.create(code: 'USD', name: 'USD')
Currency.create(code: 'AUD', name: 'Australian Dollar')
Currency.create(code: 'BGN', name: 'Bulgarian Lev')
Currency.create(code: 'BRL', name: 'Brazilian Real')
Currency.create(code: 'CAD', name: 'Canadian Dollar')
Currency.create(code: 'CHF', name: 'Swiss Franc')
Currency.create(code: 'CNY', name: 'Chinese Yuan')
Currency.create(code: 'CZK', name: 'Czech Koruna')
Currency.create(code: 'DKK', name: 'Danish Krone')
Currency.create(code: 'GBP', name: 'British Pound')
Currency.create(code: 'HKD', name: 'Hong Kong Dollar')
Currency.create(code: 'HRK', name: 'Croatian Kuna')
Currency.create(code: 'IDR', name: 'Indonesian Rupiah')
Currency.create(code: 'ILS', name: 'Israeli New Shekel')
Currency.create(code: 'INR', name: 'Indian Rupee')
Currency.create(code: 'KRW', name: 'South Korean Won')
Currency.create(code: 'MXN', name: ' Mexican Peso')
Currency.create(code: 'NOK', name: ' Norwegian Krone')
Currency.create(code: 'NZD', name: 'New Zealand Dollar')
Currency.create(code: 'PHP', name: ' Philippine Peso')
Currency.create(code: 'PLN', name: 'Polish Zloty')
Currency.create(code: 'RON', name: 'Romanian Leu')
Currency.create(code: 'RUB', name: 'Russian Ruble')
Currency.create(code: 'SEK', name: 'Swedish Krona')
Currency.create(code: 'SGD', name: 'Singapore Dollar')
Currency.create(code: 'THB', name: 'Thai Baht')
Currency.create(code: 'TRY', name: 'Turkish Lira')
Currency.create(code: 'ZAR', name: 'South African Rand')